name: Deploy ASP.NET Core API to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.202'

    - name: Build
      run: dotnet publish RentBridge.API/RentBridge.API.csproj --configuration Release

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: rentbrigeapp
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
