name: Self-Hosted Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop and clean old containers
      run: docker-compose -f compose.yaml down

    - name: Pull images and build
      run: |
        docker-compose -f compose.yaml pull
        docker-compose -f compose.yaml up -d --build
